### ISSUE TITLE
Shader error in 'ShadowBlurMoments.compute': All kernels must use same constant buffer layouts; 'blurWeightsStorage' property found to be different

### ISSUE THREAD

**Issue by michael-nischt** [Unity-Technologies/ScriptableRenderPipeline#1162]
After installing 'Render-pipelines.core' 1.1.2 via the package manager (on Unity 2018.1.0b13 - experimental Linux Editor) I get the following error statement:

`Shader error in 'ShadowBlurMoments.compute': All kernels must use same constant buffer layouts; 'blurWeightsStorage' property found to be different`

**Comment by DethRaid** [comment]
I've also encountered this. I'm on the 2018.1 editor and am using DirectX 11 on Windows 10

**Comment by sebastienlagarde** [comment]
@uygar3d is it still the case?

**Comment by TheFishInABowl** [comment]
I get this in the LW-VR-RP aswell.

**Comment by ap-chuan** [comment]
Getting this error in 2018.1.0 F2 / LTRP as well. It's been flagged as " fixed " on the issue tracker but the bug is still there. Please revise your testing procedures :   
[ https://issuetracker.unity3d.com/issues/ltrp-switching-to-android-platform-gives-shader-error-in-shadowblurmoments-dot-compute-all-kernels-dot-dot-dot-error-in-the-console ]

**Comment by unity3d-kr** [comment]
This bug show on Android platform.

I try to fix this bug. If you need it. Download here.
https://github.com/unity3d-kr/ScriptableRenderPipeline
