### ISSUE TITLE
All Meshes Invisible in Android Build LWRP

### ISSUE THREAD

**Issue by McGunn** [Unity-Technologies/ScriptableRenderPipeline#1316]
I can't for the life of me get any meshes to render at all in my Android build. It runs fine in-editor and it runs fine built in 2017.3 with no scriptable render pipeline.
I'm using 2018.1.0f2
pipelines.core and pipelines.lightweight imported through package manager.
I've tried lightweight standard PBR and simple lighting, I've tried lightweight unlit, and I've tried a few of my shader graph shaders. No meshes at all render on android (Galaxy Note 4). UI and sprite renderers render just fine. And again it works properly in the editor.
I was getting errors when I tried to run "Generate Shader Includes" but then I went into appdata and unchecked read only on all the pipeline files, and the error stopped. When I run a build I see it generating all the shader variants for the lightweight pipeline. But still, no meshes render on my phone.

Edit: Actully. Lightweight/Standard Unlit DOES render on my phone, but only when Surface Type is set to Transparent. It won't render when set to Opaque.

Edit 2: Interestingly if I change the render queue to transparent on any of these materials they render, albeit as if they were transparent (you can see through them)

**Comment by sebastienlagarde** [comment]
@phi-lira any though?

**Comment by phi-lira** [comment]
Hi @McGunn, are you having this issue while on VR?

**Comment by McGunn** [comment]
@phi-lira No, this is not in VR. Any time I build for Android I get these results. It's now been tested multiple phones with different OS versions as well. Note 4, S7, S9.

**Comment by phi-lira** [comment]
Could you guys provide a repro project so I can take a look?

**Comment by VadimTikhonyuk** [comment]
@phi-lira 
Unity 2018.1.0f2 -> Package Manager -> core & lightweight 1.1.5 ->
Set LWP in Graphics Settings -> Update Materials under LWP -> add Cube on scene with shader(lightweightPipeline/...) -> And Build under Oculus (GearVr)

**Comment by VadimTikhonyuk** [comment]
I have same problem, tried to take 1.1.8 from github dev branch, but all shaders there compiling with a lot of errors

**Comment by amitchai** [comment]
Same issue. Gear VR/ Invisible on device.

**Comment by phi-lira** [comment]
@VadimTikhonyuk @amitchai VR has indeed an issue and there's a fix on flight for 18.2, backport coming soon to 18.1. #1017 

I've asked OP about a repro scene for this as he says this issue he is reporting is not VR related.

**Comment by AlexandreFiset** [comment]
Btw this is still a bug as of 2018-06-01, using the latest packages available for 2018.2. Tried with and without post-process, tested on Oculus Go. It just renders all black.

**Comment by TheBricktop** [comment]
Latest packages  and unity 2018.1, all rendered black on gearvr and s8

**Comment by phi-lira** [comment]
Hey guys, sorry about the late responses. It seems there's still an issue in engine side regarding MSAA and Texture2DArray. Could you guys test with the following setup:

1) Pull 2.0.3-preview and disable MSAA in the pipeline asset

**Comment by coding-juan** [comment]
@phi-lira I've tested the sample scene disabling the MSAA in multiple versions of the lightweight pipeline, still, it only renders black, thanks for the suggestion though

**Comment by phi-lira** [comment]
@brandon-unity Do you have any idea what might be causing this?

**Comment by phi-lira** [comment]
@brandon-unity3d Do you have ideas of what might be the issue here?

**Comment by brandon-unity3d** [comment]
Make sure that MSAA is disabled in the quality settings.

**Comment by coding-juan** [comment]
There is no MSAA option in quality settings (not that I can see) since the render pipeline is in use (based on the message at the top)
![image](https://user-images.githubusercontent.com/10898933/41559823-8e97470e-7345-11e8-8d87-9fa22df4ab56.png)

And in the pipeline settings, it is disabled
![image](https://user-images.githubusercontent.com/10898933/41559834-998e3bb8-7345-11e8-8e9a-ef663b59e213.png)

**Comment by brandon-unity3d** [comment]
Thanks!  What about your Camera?  Is allow msaa disabled on it?

**Comment by coding-juan** [comment]
Yes ![image](https://user-images.githubusercontent.com/10898933/41562459-f1c26866-734c-11e8-81a8-13ccd76e1b97.png)

Here is what I see on the phone when VR (both cardboard or daydream) is enabled, in case it throws more insight 
![image](https://user-images.githubusercontent.com/10898933/41562598-64e9f34a-734d-11e8-9cc6-2bbf97b7bbb1.png)

If you need anything else to help troubleshoot this just ask for it, thanks for being so patient.

**Comment by brandon-unity3d** [comment]
No problem.  @coding-juan, could you also be so kind as to include a screen cap of your XR player settings?  Thank you as well for your patience!

**Comment by coding-juan** [comment]
@brandon-unity3d Of course, I have configured this in multiple ways, right now I have it like this:
![image](https://user-images.githubusercontent.com/10898933/41566533-376ba5da-735c-11e8-9fdb-94bfc97888d6.png)
I have also used "Multi Pass", and Cardboard instead of Daydream, none of them seem to work, the interesting thing is, that if you put "None" on the first place it renders nicely, you lose the VR capabilities but renders, I am gonna try to change the display mode at runtime to see if it changes something in the behaviour.
I am also pasting a screen cap of the rendering settings:
![image](https://user-images.githubusercontent.com/10898933/41566650-abf7891e-735c-11e8-8b4a-c94c0e2a5069.png)
I have tried setting the Color Space at both, Gamma and Linear without a change in the output.

**Comment by coding-juan** [comment]
As I said yesterday, I have tried to change from non-VR to VR at runtime, the results have been the same, non-VR works fine but at the moment you switch to VR it simply renders black, I also tried to make a little bit of debugging and launched an adb logcat:
```shell
--------- beginning of system
--------- beginning of main
06-19 18:20:52.590  2167  2186 I Unity   : SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 8, Memory = 3458mb
06-19 18:20:52.590  2167  2186 I Unity   : SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
06-19 18:20:52.591  2167  2186 I Unity   : ApplicationInfo com.RaraAvisLab.Test version 0.1 build c38d3d22-21bf-4dba-a4f6-537d594dbea9
06-19 18:20:52.591  2167  2186 I Unity   : Built from '2018.2/staging' branch, Version '2018.2.0b8 (fed204371f5a)', Build type 'Release', Scripting Backend 'mono'
06-19 18:20:52.691  2167  2186 E Unity   : Unable to find libAudioPluginOculusSpatializer
06-19 18:20:52.693  2167  2186 E Unity   : Unable to find libaudioplugingvrunity
06-19 18:20:52.711  2167  2186 D Unity   :  GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_sliced_3d GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_
06-19 18:20:52.711  2167  2186 D Unity   : to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic GL_EXT_robustness GL_EXT_draw_buffers_indexed GL_OES_draw_buffers_indexed GL_EXT_texture_border_clamp GL_OES_texture_border_clamp GL_EXT_texture_cube_map_array GL_OES_texture_cube_map_array GL_OES_sample_variables GL_OES_sample_shading GL_OES_shader_multisample_interpolation GL_EXT_shader_io_blocks GL_OES_shader_io_blocks GL_EXT_tessellation_shader GL_OES_tessellation_shader GL_EXT_primitive_bounding_box GL_OES_primitive_bounding_box GL_EXT_geometry_shader GL_OES_geometry_shader GL_ANDROID_extension_pack_es31a GL_EXT_gpu_shader5 GL_OES_gpu_shader5 GL_EXT_texture
06-19 18:20:52.711  2167  2186 D Unity   : _buffer GL_OES_texture_buffer GL_EXT_copy_image GL_OES_copy_image GL_EXT_shader_non_constant_global_initializers GL_EXT_color_buffer_half_float GL_EXT_color_buffer_float GL_EXT_YUV_target GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture GL_KHR_robustness GL_KHR_robust_buffer_access_behavior GL_EXT_draw_elements_base_vertex GL_OES_draw_elements_base_vertex GL_EXT_protected_textures
06-19 18:20:59.056  2167  2186 I Unity   : Created eye textures with a "separate" layout.  The "multiview" stereo mode will be used.
06-19 18:20:59.056  2167  2186 I Unity   :
06-19 18:20:59.056  2167  2186 I Unity   :
06-19 18:20:59.056  2167  2186 I Unity   : (Filename:  Line: 2158)
06-19 18:20:59.056  2167  2186 I Unity   :
06-19 18:20:59.104  2167  2186 W Unity   : Scriptable Render Pipeline stereo support requires single-pass stereo.
06-19 18:20:59.104  2167  2186 W Unity   :
06-19 18:20:59.104  2167  2186 W Unity   : (Filename:  Line: 0)
06-19 18:20:59.104  2167  2186 W Unity   :
```

**Comment by brandon-unity3d** [comment]
Based on the log message "Scriptable Render Pipeline stereo support requires single-pass stereo." it looks like your project is trying to use the multi-pass stereo rendering path.  However, multi-pass is not compatible with the scriptable render pipeline.

**Comment by coding-juan** [comment]
So I assume that this is caused because my device is not capable of using single-pass, since I hace single-pass configured, there is any workaround? Maybe editing the lightweight render pipeline? Will multi-pass be supported within it any time soon?

**Comment by brandon-unity3d** [comment]
Currently, we have no plans to support multi-pass in the scriptable render pipeline for performance reasons.  However, your console output is a bit strange.  Your output says that it is attempting to use multi-view which is supported however you are trying to use separate eye textures instead of a texture array.  Separate eye texture usage is typical for multi-pass.  I am going to dig into our native code a bit more and try to understand why you are getting that permutation.

**Comment by brandon-unity3d** [comment]
@coding-juan for clarity, which version of Unity and LWRP are you using?  Thanks!

**Comment by coding-juan** [comment]
Unity: 2018.2.0b8
LWRP: 2.0.3

**Comment by coding-juan** [comment]
Maybe it has something to do with this? https://docs.unity3d.com/2018.2/Documentation/Manual/Android-SinglePassStereoRendering.html
As I understand it, I should create a custom shader based on the LightweightPipeline/Standard (don't know if choosing physically based or simple lightning matters) and add the specifications listed in that documentation page?

**Comment by brandon-unity3d** [comment]
I tested a custom scene with Unity 2018.2.0b6 alongside LWRP 2.0.3 on a Samsung S8 with the Oculus SDK enabled.  My scene consists on several objects using the LWRP standard shader.  Also,  I have no post processing volume or post processing component on my main camera.  This is because post processing is not fully supported with single pass instancing at the moment.  If "Allow MSAA" is enabled on my main scene camera, the S8 will render a black screen only.  However, I disable "Allow MSAA" on my main camera, the scene renders as expected on the S8.  Also, my Samsung's S8 eye texture creation message looks like so,

"Created eye textures with a "texture array" layout.  The "multiview" stereo mode will be used."  which is what is to be expected on that device.

**Comment by coding-juan** [comment]
Okay, I will test again from scratch, maybe I misconfigured some parameter along the way.

**Comment by brandon-unity3d** [comment]
I just tried the same test project with daydream and I see the same behaviour you were describing.  So perhaps the issue is with the daydream sdk.  It may not contain support for texture arrays which would be an issue.  I will take a look.

Daydream SDK output
Created eye textures with a "separate" layout.  The "multiview" stereo mode will be used.

**Comment by coding-juan** [comment]
With Oculus/Gear works fine, the problem also happens with Cardboard SDK, it would be nice to be able to use either one of these since our target needs to be more open. Thank you for everything.

**Comment by brandon-unity3d** [comment]
@coding-juan , my pleasure.  Thank you for your assistance as well.
I did some more probing and found that the Daydream support doesn't play nicely with multiview rendering in the builtin renderer either.  That means this isn't an issue specific to LWRP.  I will look into understanding why that is the case.

**Comment by FlorinUnity** [comment]
Hi,
we moved this issue to our internal bug reporting tool.
You can follow it via this link:

https://issuetracker.unity3d.com/issues/lwrp-all-meshes-invisible-in-android-build-lwrp
